import torch.nn.functional as F
import torch.nn as nn

# For CIFAR-10 dataset
class CNNModel(nn.Module):
    def __init__(self):
        super(CNNModel, self).__init__()
        self.conv1 = nn.Conv2d(3, 264, kernel_size=4, padding='same')
        self.bn1 = nn.BatchNorm2d(264)
        self.conv2 = nn.Conv2d(264, 128, kernel_size=4, padding='same')
        self.bn2 = nn.BatchNorm2d(128)
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)
        self.drop1 = nn.Dropout(0.2)
        self.conv3 = nn.Conv2d(128, 512, kernel_size=4, padding='same')
        self.bn3 = nn.BatchNorm2d(512)
        self.conv4 = nn.Conv2d(512, 128, kernel_size=4, padding='same')
        self.bn4 = nn.BatchNorm2d(128)
        self.drop2 = nn.Dropout(0.25)
        self.conv5 = nn.Conv2d(128, 128, kernel_size=4, padding='same')
        self.bn5 = nn.BatchNorm2d(128)
        self.conv6 = nn.Conv2d(128, 128, kernel_size=4, padding='same')
        self.bn6 = nn.BatchNorm2d(128)
        self.drop3 = nn.Dropout(0.35)
        self.fc1 = nn.Linear(128 * 4 * 4, 256)
        self.bn7 = nn.BatchNorm1d(256)
        self.drop4 = nn.Dropout(0.5)
        self.fc2 = nn.Linear(256, 10)

    def forward(self, x):
        x = F.relu(self.bn1(self.conv1(x)))
        x = F.relu(self.bn2(self.conv2(x)))
        x = self.pool(x)
        x = self.drop1(x)
        x = F.relu(self.bn3(self.conv3(x)))
        x = F.relu(self.bn4(self.conv4(x)))
        x = self.pool(x)
        x = self.drop2(x)
        x = F.relu(self.bn5(self.conv5(x)))
        x = F.relu(self.bn6(self.conv6(x)))
        x = self.pool(x)
        x = self.drop3(x)
        x = x.view(-1, 128 * 4 * 4)
        x = F.relu(self.bn7(self.fc1(x)))
        x = self.drop4(x)
        policy_output = self.fc2(x)
        return policy_output
    
# For CIFAR-10 dataset with Reinforcement Learning
class CNNModelRL(nn.Module):
    def __init__(self):
        super(CNNModelRL, self).__init__()
        self.conv1 = nn.Conv2d(3, 264, kernel_size=4, padding='same')
        self.bn1 = nn.BatchNorm2d(264)
        self.conv2 = nn.Conv2d(264, 128, kernel_size=4, padding='same')
        self.bn2 = nn.BatchNorm2d(128)
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)
        self.drop1 = nn.Dropout(0.2)
        self.conv3 = nn.Conv2d(128, 512, kernel_size=4, padding='same')
        self.bn3 = nn.BatchNorm2d(512)
        self.conv4 = nn.Conv2d(512, 128, kernel_size=4, padding='same')
        self.bn4 = nn.BatchNorm2d(128)
        self.drop2 = nn.Dropout(0.25)
        self.conv5 = nn.Conv2d(128, 128, kernel_size=4, padding='same')
        self.bn5 = nn.BatchNorm2d(128)
        self.conv6 = nn.Conv2d(128, 128, kernel_size=4, padding='same')
        self.bn6 = nn.BatchNorm2d(128)
        self.drop3 = nn.Dropout(0.35)
        self.fc1 = nn.Linear(128 * 4 * 4, 256)
        self.bn7 = nn.BatchNorm1d(256)
        self.drop4 = nn.Dropout(0.5)
        self.classifier = nn.Linear(256, 10)

    def forward(self, x):
        x = F.relu(self.bn1(self.conv1(x)))
        x = F.relu(self.bn2(self.conv2(x)))
        x = self.pool(x)
        x = self.drop1(x)
        x = F.relu(self.bn3(self.conv3(x)))
        x = F.relu(self.bn4(self.conv4(x)))
        x = self.pool(x)
        x = self.drop2(x)
        x = F.relu(self.bn5(self.conv5(x)))
        x = F.relu(self.bn6(self.conv6(x)))
        x = self.pool(x)
        x = self.drop3(x)
        x = x.view(-1, 128 * 4 * 4)
        x = F.relu(self.bn7(self.fc1(x)))
        x = self.drop4(x)
        policy_output = self.classifier(x)
        return policy_output
    
# For CIFAR-100 dataset
class CNNModelforCifar100(nn.Module):
    def __init__(self):
        super(CNNModelforCifar100, self).__init__()
        self.conv1 = nn.Conv2d(3, 264, kernel_size=4, padding='same')
        self.bn1 = nn.BatchNorm2d(264)
        self.conv2 = nn.Conv2d(264, 128, kernel_size=4, padding='same')
        self.bn2 = nn.BatchNorm2d(128)
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)
        self.drop1 = nn.Dropout(0.2)
        self.conv3 = nn.Conv2d(128, 512, kernel_size=4, padding='same')
        self.bn3 = nn.BatchNorm2d(512)
        self.conv4 = nn.Conv2d(512, 128, kernel_size=4, padding='same')
        self.bn4 = nn.BatchNorm2d(128)
        self.drop2 = nn.Dropout(0.25)
        self.conv5 = nn.Conv2d(128, 128, kernel_size=4, padding='same')
        self.bn5 = nn.BatchNorm2d(128)
        self.conv6 = nn.Conv2d(128, 128, kernel_size=4, padding='same')
        self.bn6 = nn.BatchNorm2d(128)
        self.drop3 = nn.Dropout(0.35)
        self.fc1 = nn.Linear(128 * 4 * 4, 256)
        self.bn7 = nn.BatchNorm1d(256)
        self.drop4 = nn.Dropout(0.5)
        self.fc2 = nn.Linear(256, 100)

    def forward(self, x):
        x = F.relu(self.bn1(self.conv1(x)))
        x = F.relu(self.bn2(self.conv2(x)))
        x = self.pool(x)
        x = self.drop1(x)
        x = F.relu(self.bn3(self.conv3(x)))
        x = F.relu(self.bn4(self.conv4(x)))
        x = self.pool(x)
        x = self.drop2(x)
        x = F.relu(self.bn5(self.conv5(x)))
        x = F.relu(self.bn6(self.conv6(x)))
        x = self.pool(x)
        x = self.drop3(x)
        x = x.view(-1, 128 * 4 * 4)
        x = F.relu(self.bn7(self.fc1(x)))
        x = self.drop4(x)
        policy_output = self.fc2(x)
        return policy_output
    
# For ImageNet-100 dataset
class CNNModelforImagenet100(nn.Module):
    def __init__(self):
        super(CNNModelforImagenet100, self).__init__()
        self.conv1 = nn.Conv2d(3, 264, kernel_size=4, padding='same')
        self.bn1 = nn.BatchNorm2d(264)
        self.conv2 = nn.Conv2d(264, 128, kernel_size=4, padding='same')
        self.bn2 = nn.BatchNorm2d(128)
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)
        self.drop1 = nn.Dropout(0.2)
        self.conv3 = nn.Conv2d(128, 512, kernel_size=4, padding='same')
        self.bn3 = nn.BatchNorm2d(512)
        self.conv4 = nn.Conv2d(512, 128, kernel_size=4, padding='same')
        self.bn4 = nn.BatchNorm2d(128)
        self.drop2 = nn.Dropout(0.25)
        self.conv5 = nn.Conv2d(128, 128, kernel_size=4, padding='same')
        self.bn5 = nn.BatchNorm2d(128)
        self.conv6 = nn.Conv2d(128, 128, kernel_size=4, padding='same')
        self.bn6 = nn.BatchNorm2d(128)
        self.drop3 = nn.Dropout(0.35)
        self.fc1 = nn.Linear(128 * 4 * 4, 256)
        self.bn7 = nn.BatchNorm1d(256)
        self.drop4 = nn.Dropout(0.5)
        self.fc2 = nn.Linear(256, 100)

    def forward(self, x):
        x = F.relu(self.bn1(self.conv1(x)))
        x = F.relu(self.bn2(self.conv2(x)))
        x = self.pool(x)
        x = self.drop1(x)
        x = F.relu(self.bn3(self.conv3(x)))
        x = F.relu(self.bn4(self.conv4(x)))
        x = self.pool(x)
        x = self.drop2(x)
        x = F.relu(self.bn5(self.conv5(x)))
        x = F.relu(self.bn6(self.conv6(x)))
        x = self.pool(x)
        x = self.drop3(x)
        x = x.view(-1, 128 * 4 * 4)
        x = F.relu(self.bn7(self.fc1(x)))
        x = self.drop4(x)
        policy_output = self.fc2(x)
        return policy_output
    
# For Places365 dataset
class CNNModelforPlaces365(nn.Module):
    def __init__(self):
        super(CNNModelforPlaces365, self).__init__()
        self.conv1 = nn.Conv2d(3, 264, kernel_size=4, padding='same')
        self.bn1 = nn.BatchNorm2d(264)
        self.conv2 = nn.Conv2d(264, 128, kernel_size=4, padding='same')
        self.bn2 = nn.BatchNorm2d(128)
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)
        self.drop1 = nn.Dropout(0.2)
        self.conv3 = nn.Conv2d(128, 512, kernel_size=4, padding='same')
        self.bn3 = nn.BatchNorm2d(512)
        self.conv4 = nn.Conv2d(512, 128, kernel_size=4, padding='same')
        self.bn4 = nn.BatchNorm2d(128)
        self.drop2 = nn.Dropout(0.25)
        self.conv5 = nn.Conv2d(128, 128, kernel_size=4, padding='same')
        self.bn5 = nn.BatchNorm2d(128)
        self.conv6 = nn.Conv2d(128, 128, kernel_size=4, padding='same')
        self.bn6 = nn.BatchNorm2d(128)
        self.drop3 = nn.Dropout(0.35)
        self.fc1 = nn.Linear(128 * 4 * 4, 256)
        self.bn7 = nn.BatchNorm1d(256)
        self.drop4 = nn.Dropout(0.5)
        self.fc2 = nn.Linear(256, 365)

    def forward(self, x):
        x = F.relu(self.bn1(self.conv1(x)))
        x = F.relu(self.bn2(self.conv2(x)))
        x = self.pool(x)
        x = self.drop1(x)
        x = F.relu(self.bn3(self.conv3(x)))
        x = F.relu(self.bn4(self.conv4(x)))
        x = self.pool(x)
        x = self.drop2(x)
        x = F.relu(self.bn5(self.conv5(x)))
        x = F.relu(self.bn6(self.conv6(x)))
        x = self.pool(x)
        x = self.drop3(x)
        x = x.view(-1, 128 * 4 * 4)
        x = F.relu(self.bn7(self.fc1(x)))
        x = self.drop4(x)
        policy_output = self.fc2(x)
        return policy_output